import { CaretRight, MagnifyingGlass, XCircle } from '@phosphor-icons/react/dist/ssr'
import { hasLocale } from 'next-intl'
import { getTranslations, setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { BackLink } from '@/components/layout/back-link'
import { RomajiDisclosure } from '@/components/sake/romaji-disclosure'
import { SakenowaAttribution } from '@/components/sake/sakenowa-attribution'
import { getPathname, Link } from '@/i18n/navigation'
import { routing } from '@/i18n/routing'
import {
  isCatalogueQuerySpecific,
  MAX_CATALOGUE_SEARCH_RESULTS,
  searchCatalogue,
  type CatalogueSearchResult,
} from '@/lib/sakenowa/search-brands'

/**
 * §8 Search ("Type it") — `/[locale]/search`.
 *
 * The cheap half of the product. A visitor who can read the bottle does not
 * need a camera or a model: they need the catalogue row. This is also the
 * deterministic alternative to `/suggest`, which runs the AI SDK tool loop at
 * a paid call per question — so every scan dead-end that used to bridge there
 * now has somewhere cheaper to go.
 *
 * **No client components, on purpose.** The field is a plain GET form: typing
 * and pressing Enter navigates to `?q=…`, the server renders the matches, and
 * the whole thing works with JavaScript off and needs no debounce, no
 * `useState`, and no loading state. §8 specifies no as-you-type behaviour, so
 * there is nothing to give up. "Clear" is a link back to `/search` rather than
 * a button that resets state, for the same reason.
 *
 * Age gating is the proxy's job: `/search` is absent from
 * `UNGATED_LOCALE_PATHS`, which is deny-by-default, so a visitor who has not
 * accepted the 18+ gate never reaches this component — and it shows brand
 * data, so that matters (JMStV, ADR-0006).
 *
 * **Three things §8 draws that the data cannot fill**, all documented in
 * `search-brands.ts`: the per-row thumb (Sakenowa ships no images — #308 §7),
 * the "Tasted" tag and "Recently tasted" empty state (the journal is
 * maintainer-only per ADR-0020, so for almost every visitor both would always
 * be blank), and the dashed "Add {query} yourself" row (manual entry is §5's
 * Phase-2 "Added by you", and #162 forbids advertising a surface that does not
 * exist). The empty state says what the field is for instead.
 *
 * `<SakenowaAttribution />` is required — these are Sakenowa brand rows.
 *
 * **The romaji on each row is not**, which is why `<RomajiDisclosure />` sits
 * beside it. Sakenowa publishes Japanese names only; `name_romaji` is a
 * Hepburn reading generated by Anthropic Haiku during `pnpm ingest`, which
 * ADR-0005 classes `llm_inferred` and the bottle page already badges as such.
 * A chip on twenty rows would bury the names it annotates and repeat one
 * identical claim twenty times, so the list takes §16's shape instead: one
 * caveat line, the explanation a tap away, and the caveat reachable by
 * assistive tech with no interaction. The kanji, brand ids and brewery names
 * ARE canonical `sakenowa`, and carry nothing.
 */

interface PageProps {
  params: Promise<{ locale: string }>
  searchParams: Promise<{ q?: string | string[] }>
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) return {}
  const t = await getTranslations({ locale, namespace: 'search' })
  return { title: `${t('title')} | Yawaragi` }
}

/** A repeated `?q=` yields an array; take the first and ignore the rest. */
function firstQueryValue(value: string | string[] | undefined): string {
  if (Array.isArray(value)) return value[0] ?? ''
  return value ?? ''
}

export default async function SearchPage({ params, searchParams }: PageProps) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) notFound()
  setRequestLocale(locale)

  const query = firstQueryValue((await searchParams).q).slice(0, 80)
  const t = await getTranslations('search')
  const tHeader = await getTranslations('header')

  const specific = isCatalogueQuerySpecific(query)
  // `searchCatalogue` never throws — a mirror failure comes back as
  // `unavailable` rather than 500ing a screen whose field, empty state and
  // camera bridge all still work. See its docstring for why this surface
  // degrades where `/sake/*` does not.
  const outcome = specific ? await searchCatalogue(query) : ({ kind: 'ok', matches: [] } as const)
  const matches = outcome.kind === 'ok' ? outcome.matches : []

  // Back goes to the scan screen for a cold deep-link: §8 is reached from
  // there ("Type it"), so that is where a visitor with no history came from in
  // every path we ship.
  const scanHref = getPathname({ locale, href: '/scan' })

  return (
    <main
      className="mx-auto flex w-full max-w-3xl flex-col gap-5 px-5 py-6"
      data-testid="search-page"
    >
      {/* §8's top row: back · the field. `-ml-3` pulls the 44px target back so
          the glyph lines up with the page gutter. */}
      <div className="flex items-center gap-2">
        <span className="-ml-3 flex">
          <BackLink fallbackHref={scanHref} label={tHeader('backLabel')} />
        </span>
        {/*
          §8: "44px field, accent-500 border, autofocus". A GET form, so Enter
          submits with no JavaScript. `autoFocus` is an HTML attribute here,
          not an effect — the field is focused before hydration would have run.
        */}
        <form action="" method="get" className="flex min-w-0 flex-1 items-center gap-2">
          <label
            className="flex h-11 min-w-0 flex-1 items-center gap-2 rounded-md border border-ginshu-500 bg-surface px-3"
            data-testid="search-field"
          >
            <MagnifyingGlass size={17} className="shrink-0 text-ash-600" aria-hidden="true" />
            <span className="sr-only">{t('fieldLabel')}</span>
            <input
              // `type="text"` with the searchbox role, not `type="search"`.
              // Chrome paints `type="search"` its own clear button — bright
              // blue, off-palette on a warm dark ground, and a second control
              // doing what the ✕ beside it already does. Hiding it means
              // fighting a UA pseudo-element whose computed style is not even
              // readable from script, so it is simpler not to summon it: the
              // role carries the same semantics to assistive tech, and
              // `inputMode`/`enterKeyHint` carry the same keyboard hints.
              type="text"
              role="searchbox"
              inputMode="search"
              name="q"
              defaultValue={query}
              // §8 specifies autofocus, and the field is the entire purpose of
              // this screen — focus is not being taken from anything the
              // visitor was using. No lint suppression needed: the repo's
              // config does not enable `jsx-a11y/no-autofocus`.
              autoFocus
              maxLength={80}
              enterKeyHint="search"
              autoComplete="off"
              placeholder={t('placeholder')}
              className="min-w-0 flex-1 bg-transparent text-card-heading text-ink placeholder:text-ash-500 focus:outline-none"
              data-testid="search-input"
            />
            {query.length > 0 && (
              // §8 draws the clear affordance INSIDE the field. A link back to
              // the bare route, not a reset button, so it works with no
              // JavaScript like the rest of this screen.
              <Link
                href="/search"
                aria-label={t('clear')}
                className="-mr-1 inline-flex size-9 shrink-0 items-center justify-center rounded-full text-ash-600 transition-colors hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ginshu-600"
                data-testid="search-clear"
              >
                <XCircle size={17} aria-hidden="true" />
              </Link>
            )}
          </label>
          <button type="submit" className="sr-only" data-testid="search-submit">
            {t('submit')}
          </button>
        </form>
      </div>

      {query.length === 0 ? (
        <section className="flex flex-col gap-2" data-testid="search-empty">
          <h1 className="text-card-heading font-medium text-ink">{t('emptyTitle')}</h1>
          {/* §8's own empty state is "Recently tasted", which needs a journal
              this visitor almost certainly does not have (ADR-0020). Saying
              what the field reads, and how much is in there, is the honest
              substitute. */}
          <p className="text-body text-ash-600">{t('emptyBody', { count: CATALOGUE_SIZE })}</p>
        </section>
      ) : !specific ? (
        <p className="text-body text-ash-600" data-testid="search-too-short">
          {t('tooShort')}
        </p>
      ) : outcome.kind === 'unavailable' ? (
        <section className="flex flex-col gap-2" data-testid="search-unavailable">
          <h1 className="text-card-heading font-medium text-ink">{t('unavailableTitle')}</h1>
          {/* Distinct from "nothing matches" on purpose: that would be a lie,
              and the one a visitor acts on by retyping their query. Says whose
              fault it is, and still offers the other way in (#162). */}
          <p className="text-body text-ash-600">{t('unavailableBody')}</p>
          <Link
            href="/scan"
            className="w-fit rounded-sm text-body font-medium text-ginshu-700 underline underline-offset-4 hover:text-ginshu-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ginshu-600"
            data-testid="search-unavailable-scan"
          >
            {t('noMatchScanCta')}
          </Link>
        </section>
      ) : matches.length === 0 ? (
        <section className="flex flex-col gap-2" data-testid="search-no-match">
          <h1 className="text-card-heading font-medium text-ink">{t('noMatchTitle')}</h1>
          <p className="text-body text-ash-600">{t('noMatchBody')}</p>
          {/* Not a dead end (#162): the other way to identify a bottle. */}
          <Link
            href="/scan"
            className="w-fit rounded-sm text-body font-medium text-ginshu-700 underline underline-offset-4 hover:text-ginshu-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ginshu-600"
            data-testid="search-no-match-scan"
          >
            {t('noMatchScanCta')}
          </Link>
        </section>
      ) : (
        <>
          {/* `MAX_CATALOGUE_SEARCH_RESULTS` rows back means there may be
              more — reporting the cap as a total would be false. Said as
              "first N" rather than spending a COUNT round-trip to render a
              number nobody acts on. */}
          <h1 className="text-section-label uppercase text-ash-600" data-testid="search-count">
            {matches.length === MAX_CATALOGUE_SEARCH_RESULTS
              ? t('matchesCapped', { count: matches.length })
              : t('matches', { count: matches.length })}
          </h1>
          <ol className="flex flex-col" data-testid="search-results">
            {matches.map((match) => (
              <SearchResultRow
                key={match.brandId}
                match={match}
                breweryUnknown={t('breweryUnknown')}
              />
            ))}
          </ol>
          {/* Every row is a Sakenowa brand row, so attribution is not optional
              (ADR-0014). Inline, because the list is the subject rather than
              any single record — and next to it, the one part of each row that
              is NOT Sakenowa's. */}
          <div className="flex flex-col gap-1.5">
            <SakenowaAttribution placement="inline" />
            <RomajiDisclosure id="search-romaji" />
          </div>
        </>
      )}
    </main>
  )
}

/**
 * Catalogue size, for the empty state's "{count} sakes are in the catalogue".
 *
 * A constant rather than a `SELECT count(*)`: the empty state runs on every
 * visit to `/search` with no query, and spending a round-trip to render a
 * number that moves a few times a year is the wrong trade. It is a claim about
 * our mirror, so it is rounded DOWN to the nearest hundred — the sentence
 * stays true as rows are added, and never overstates.
 *
 * Measured 2026-09-30: 3,315 brands. Re-round when `pnpm ingest` moves it past
 * the next hundred.
 */
const CATALOGUE_SIZE = 3300

/**
 * One §8 row: name · romaji · brewery, on the divider-bottom list vocabulary
 * the prototype uses here and in §6.
 *
 * Tapping opens the bottle page. §8 says "result card", which in the design is
 * the one screen reached from scan, search and manual entry alike; ours is
 * `/sake/[brandId]`, which is where §6's rows go too.
 */
function SearchResultRow({
  match,
  breweryUnknown,
}: {
  match: CatalogueSearchResult
  breweryUnknown: string
}) {
  return (
    <li>
      <Link
        href={{ pathname: '/sake/[brandId]', params: { brandId: String(match.brandId) } }}
        className="flex min-h-[58px] items-center gap-3 border-b border-divider px-1 py-2.5 transition-colors hover:bg-ash-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ginshu-600"
        data-testid="search-result-row"
      >
        <span className="flex min-w-0 flex-col gap-0.5">
          <span className="flex flex-wrap items-baseline gap-x-2">
            <span className="text-card-heading font-medium text-ink" lang="ja">
              {match.nameKanji}
            </span>
            {match.nameRomaji && (
              <span className="text-subtle text-ash-600">{match.nameRomaji}</span>
            )}
          </span>
          <span className="flex flex-wrap items-baseline gap-x-2 text-meta text-ash-600">
            {match.breweryKanji ? (
              <>
                <span lang="ja">{match.breweryKanji}</span>
                {match.breweryRomaji && <span>({match.breweryRomaji})</span>}
              </>
            ) : (
              // ~48 brands point at a placeholder brewery row. Saying so beats
              // an empty line that reads as a rendering bug.
              <span>{breweryUnknown}</span>
            )}
          </span>
        </span>
        <CaretRight size={16} className="ml-auto shrink-0 text-ash-500" aria-hidden="true" />
      </Link>
    </li>
  )
}
