-- Hand-curated romaji that wins over the LLM transliteration (CONTEXT.md
-- "Naming convention" has promised this table since #121; it was never
-- created). Sakenowa publishes only Japanese names; `name_romaji` is
-- generated by Haiku at ingest, and a check of 23 real bottles found nine
-- wrong readings among ~45 names — 瑞鷹 "Mizutaka" for Zuiyo, 天吹 "Amafuki"
-- for Amabuki, katakana leaking into "Goruド Ninki". A visitor typing the name
-- off the label could not find the sake.
--
-- An override wins on every write, through a BEFORE INSERT OR UPDATE trigger
-- on `brands` and `breweries`: the ingest keeps upserting whatever the model
-- returned and never needs to know the table exists, and a later
-- re-transliteration (when Sakenowa changes a row's kanji) cannot undo a
-- curated name. Keyed by Sakenowa id, so an override survives a renamed row;
-- if the kanji change makes the override wrong, the curator removes it.
--
-- Public catalogue data with no user identifier (ADR-0011 does not apply).
-- Nothing in the app reads it directly — only the triggers do — so it follows
-- `ingestion_runs`: RLS on, no grant, no policy for anon/authenticated.

CREATE TABLE name_romaji_overrides (
  kind        TEXT        NOT NULL CHECK (kind IN ('brand', 'brewery')),
  id          INTEGER     NOT NULL,
  name_romaji TEXT        NOT NULL CHECK (length(btrim(name_romaji)) > 0),
  -- Why the model's reading was wrong, and where the right one comes from
  -- (the label, the brewery's own site). Curation notes, not displayed.
  note        TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kind, id)
);

ALTER TABLE name_romaji_overrides ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON name_romaji_overrides FROM anon;
REVOKE ALL ON name_romaji_overrides FROM authenticated;

CREATE FUNCTION apply_brand_romaji_override() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  curated TEXT;
BEGIN
  SELECT o.name_romaji INTO curated
    FROM name_romaji_overrides o
   WHERE o.kind = 'brand' AND o.id = NEW.brand_id;
  IF FOUND THEN
    NEW.name_romaji := curated;
  END IF;
  RETURN NEW;
END;
$$;

CREATE FUNCTION apply_brewery_romaji_override() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  curated TEXT;
BEGIN
  SELECT o.name_romaji INTO curated
    FROM name_romaji_overrides o
   WHERE o.kind = 'brewery' AND o.id = NEW.brewery_id;
  IF FOUND THEN
    NEW.name_romaji := curated;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER brands_romaji_override
  BEFORE INSERT OR UPDATE ON brands
  FOR EACH ROW EXECUTE FUNCTION apply_brand_romaji_override();

CREATE TRIGGER breweries_romaji_override
  BEFORE INSERT OR UPDATE ON breweries
  FOR EACH ROW EXECUTE FUNCTION apply_brewery_romaji_override();

-- The nine readings found wrong in the maintainer's 23-bottle check
-- (2026-10-09). Each checked against the bottle label or the brewery's own
-- romanisation.
INSERT INTO name_romaji_overrides (kind, id, name_romaji, note) VALUES
  ('brand',   986, 'Zuiyo',          '瑞鷹: model read "Mizutaka"; label and brewery use Zuiyo'),
  ('brand',   973, 'Amabuki',        '天吹: model read "Amafuki"'),
  ('brand',   793, 'Hanatomoe',      '花巴: model read "Hanaba"'),
  ('brand',   952, 'Ikekame',        '池亀: model read "Ikegame"; the brewery writes Ikekame'),
  ('brand',   190, 'Gold Ninki',     'ゴールド人気: katakana leaked into the romaji ("Goruド Ninki")'),
  ('brewery', 766, 'Zuiyo Shuzo',    '瑞鷹酒造: model read "Zuio Shuzo"'),
  ('brewery', 756, 'Amabuki Shuzo',  '天吹酒造: model read "Amafuki Shuzo"'),
  ('brewery', 629, 'Rihaku Shuzo',   '李白酒造: model read "Ribaku Shuzo"'),
  ('brewery', 384, 'Tomono Shuzo',   '伴野酒造 (Sawa no Hana): model read "Banno Shuzo"');

-- Apply them to the rows already in the mirror. A no-op UPDATE fires the
-- triggers, which set the curated value.
UPDATE brands    SET name_romaji = name_romaji WHERE brand_id   IN (SELECT id FROM name_romaji_overrides WHERE kind = 'brand');
UPDATE breweries SET name_romaji = name_romaji WHERE brewery_id IN (SELECT id FROM name_romaji_overrides WHERE kind = 'brewery');
